### ISSUE TITLE
Creation of modeling projects

### ISSUE THREAD

**Issue by verenya** [CoWolf/CoWolf#304] opened 2014-09-15 06:44 UTC
To have a good usability it is necessary that the user does not have to do the connection between viewpoint and models

Finished when:
- [x] Modeling project nature is attached to cowolf projects
- [x] programmatic creation of viewpoints
- [x] filter for representation files
- [x] extension of sirius classes so that models in subfolders are found

**Comment by philippniethammer** [comment] 2014-09-15 06:46
Duplicate of #262. Copied description there.

**Closed as completed** 2014-09-15 06:46 UTC
Labels: type:task
